CREATE TABLE USER_INFO(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(100),
    USER_TRADE_PASSWORD VARCHAR(100),
    MOBILE VARCHAR(20),
    USER_ZFB  VARCHAR(20),
    REMARK  VARCHAR(20),
    PRIMARY KEY (USER_ID)
);